substitutions:
  name: "lunarsensor"
  friendly_name: "Lunar Sensor"

esphome:
  name: ${name}
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: false

esp32:
  board: esp32-c6-devkitm-1
  framework:
    type: esp-idf

logger:
  level: DEBUG

api:

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:

bluetooth_proxy:
  active: true

i2c:
  sda: GPIO2
  scl: GPIO1
  scan: false
  id: grove

sensor:
  - platform: bh1750
    name: "Ambient Light"
    id: ambient_light
    update_interval: 1s
    filters:
      - sliding_window_moving_average:
          window_size: 8
          send_every: 2
          send_first_at: 2

status_led:
  pin: GPIO7

web_server:
  port: 80